{
 "title": "GPU Nodes",
 "tags": [
  "cluster",
  "GPU"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "server",
    "query": "query_result(label_replace(DCGM_FI_DEV_POWER_USAGE{instance=~\".*:9400\"}, \"instance\", \"$1\", \"instance\", \"(.*):9400.*\"))"
   }
  ]
 },
 "panels": [
  { "title": "$hostname Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$hostname:9100\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{instance=\"$hostname:9100\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{instance=\"$hostname:9100\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=\"$hostname:9400\"})"
    }
   ]
  },
  {
   "title": "NVLINK Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "1e6*sum(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{instance=\"$hostname:9400\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$hostname:9100\"} - node_memory_MemFree_bytes{instance=\"$hostname:9100\"} - node_memory_Buffers_bytes{instance=\"$hostname:9100\"} - node_memory_Cached_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$hostname:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "singlestat",
   "description": "GPU Shutdown Temp           : 90 C\nGPU Slowdown Temp           : 87 C\nGPU Max Operating Temp      : 83 C",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=\"$hostname:9400\"})"
    }
   ]
  },
  {
   "title": "PCIe Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(DCGM_FI_DEV_PCIE_TX_THROUGHPUT{instance=\"$hostname:9400\"}[$__interval]))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(rate(DCGM_FI_DEV_PCIE_RX_THROUGHPUT{instance=\"$hostname:9400\"}[$__interval]))",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$hostname:9100\"}) - sum(node_filesystem_avail_bytes{device!=\"rootfs\",instance=\"$hostname:9100\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$hostname:9100\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$hostname:9100\"} - node_memory_MemFree_bytes{instance=\"$hostname:9100\"}  - node_memory_Buffers_bytes{instance=\"$hostname:9100\"} - node_memory_Cached_bytes{instance=\"$hostname:9100\"}) / node_memory_MemTotal_bytes{instance=\"$hostname:9100\"}) * 100"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=\"$hostname:9400\"})"
    }
   ]
  },
  {
   "title": "Ethernet Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$hostname:9100\",device=~\"en.*\"}[$__interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$hostname:9100\",device=~\"en.*\"}[$__interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$hostname:9100\"}[$__interval])",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$hostname:9100\"}[$__interval])",
     "legendFormat": "Write ({{device}})"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=\"$hostname:9100\"}[$__interval]))",
     "legendFormat": "I/O time"
    }
   ]
  },
  {
   "title": "GPU Mem Cpy Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{instance=\"$hostname:9400\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Mem. Cpy Utilization",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{instance=\"$hostname:9400\"})"
    }
   ]
  },
  {
   "title": "Infiniband Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_infiniband_port_data_transmitted_bytes_total{instance=\"$hostname:9100\"}[$__interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(node_infiniband_port_data_received_bytes_total{instance=\"$hostname:9100\"}[$__interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$hostname:9100\"}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$hostname:9100\"}"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=\"$hostname:9400\"}/(DCGM_FI_DEV_FB_USED{instance=\"$hostname:9400\"}+DCGM_FI_DEV_FB_FREE{instance=\"$hostname:9400\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "System Total Power Draw",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 21 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=\"$hostname:9100\"}"
    }
   ]
  },
  {
   "title": "System Power Draw",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 21 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=\"$hostname:9100\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 23 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_SM_CLOCK{instance=\"$hostname:9400\"}*1000000)"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 23 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_CLOCK{instance=\"$hostname:9400\"}*1000000)"
    }
   ]
  }
 ]
}